### ISSUE TITLE
a `keep-all` problem

### ISSUE THREAD

**Issue by wellsleep** [AWEEKJ/Kiko-plus#15]
https://github.com/AWEEKJ/Kiko-plus/blob/master/_sass/_typography.scss#L19

May I know why the `word-break` has to be `keep-all` here?
For English it may be all ok coz there're spaces between each words. However for Chinese (I'm not sure if Korean is impact) there's no space between each character. So when browse from mobile device (esp. for iPhone, Samsung Galaxy S is unbelievably well-rendered), if the sentence is long enough, it will stretch the width of the whole page. And that makes the page terrible.

I think it should be `word-break: normal` or just delete this expression.

**Comment by wiserain** [comment]
I agree with @wellsleep. It could be a problem especially when quoting a long URL.

**Comment by aweekj** [comment]
@wellsleep I thought `keep-all` is the solution for [white river](https://en.wikipedia.org/wiki/River_(typography)) problem. But it make sense that `keep-all` condition  with CJK language looks terrible when there is no space in long sentence. So I fixed it. Thank you.
