### ISSUE TITLE
브라우져(크롬)에서 첫 페이지 렌더가 안됩니다.

### ISSUE THREAD

**Issue by flavono123** [AWEEKJ/Kiko-plus#25]
<img width="1214" alt="kiko_plus" src="https://cloud.githubusercontent.com/assets/20619567/25554107/5023ea2c-2d00-11e7-8353-746fdf5e2f07.png">

[여기](http://jekyllthemes.org/themes/kiko-plus/)서 다운로드 한 후 
기본적으로 만든 깃페이지 로컬 레포에 복사하고 
jekyll serve --watch 했을 땐 잘 보이는데
푸시하고 크롬에서 접속하니 안보입니다.

    gem install jekyll-seo-tag jekyll-paginate jekyll-admin

로 플러그인 설치하고
_config.yml 에서 url과 baseurl만 수정했습니다.

**Comment by wiserain** [comment]
@flavono123 먼저 헤더에 뜨는 author 내용은 현재 github pages의 gem에 들어 있는 jekyll-seo-tag에 버그가 있어서 그런것 같습니다. 업데이트 되기 전까지는 ```_includes/head.html```의 ```{% seo %}```을 지우고 사용하셔야 할겁니다.

하나 더, css가 로딩이 안되는 것을 보니 baseurl 설정의 문제 같습니다.

**Comment by aweekj** [comment]
@flavono123  https://flavono123.github.io로 하시려면 `_config.yml`에서 baseurl을 없애보세요 
```
baseurl: ""
```
https://flavono123.github.io/blog 로 하시려면 새 리포지토리 만들어서 gh-pages 브랜치에 올려야 해요. 이 [블로그](https://nolboo.kim/blog/2013/10/15/free-blog-with-github-jekyll/#계정-주소-페이지)를 참고하시길.

**Comment by aweekj** [comment]
@wiserain  jekyll-seo-tag에 버그가 있나보군요. 알려주셔서 감사합니다.

**Comment by flavono123** [comment]
@wiserain @AWEEKJ 모두 감사합니다! 
baseurl 지우고 {% seo %} 지워서 잘 작동합니다.
