### ISSUE TITLE
request to add horizontal scrollbar to code block

### ISSUE THREAD

**Issue by stvhuang** [AWEEKJ/Kiko-plus#26]
I think it will improve the readability if adding a horizontal scrollbar to the code block, or the code will be wrapped.
For example, the [code](https://yanjiahuang.github.io/Kiko-plus/2013-08-16/code-highlighting-post/#standard-code-block) in "Standard Code Block" in the post "2013-08-16-code-highlighting-post.md" has been wrapped. It's hard to read, especially on a mobile device.

**Comment by aweekj** [comment]
@yanjiahuang I've accepted your opinion. Thanks.
