### ISSUE TITLE
When tapping back button on post previous selection remains highlighted on iOS safari

### ISSUE THREAD

**Issue by kekearif** [AWEEKJ/Kiko-plus#7]
Hey, if I tap back or a blog post I'm viewing in Safari on iOS the post remains highlighted in the list:

![img_0574](https://cloud.githubusercontent.com/assets/10420186/20884886/d07eadf0-bb28-11e6-9ca3-e1b2231f1e34.PNG)

Any idea why this is happening or what I can do to fix it? Thanks!

**Comment by whuang8** [comment]
In the Post section of `_site.scss`, around line 162, try the following:

```css
a:visited {
    color: #fff;
}
```

**Comment by aweekj** [comment]
@whuang8 I've updated this. Thank you!
